config/routes.rb
Startup::Application.routes.draw do

resources :projects do
  collection do
  get :top_hits
  end
end
root :to =>'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	def self.top_projects
		Project.where('budget > 100')
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :find_project , :only => [:edit, :show, :update, :destroy]
	def index
		@projects = Project.all

	end
	
	def new
		@project = Project.new
	end

	def create
		 binding.pry
		@project = Project.new(params[:project])
		if @project.save!
			redirect_to projects_path
		else
			redirect_to :back
		end
	end

	def show
		# @project = Project.find(params[:id])

	end

	def edit
		# @project = Project.find(params[:id])
	end

	def update
		# @project = Project.find(params[:id])
		# @project.update_attributes(params[:project])
		redirect_to projects_path

	end

	def destroy
		# @project = Project.find(params[:id])
		@project.destroy
		redirect_to projects_path
	end

	def top_hits
		@projects = Project.top_projects
	end

	def find_project
		@project = Project.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Startup</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<%= f.label :title, 'Title:'%>
	<%= f.text_field :title%>
	<br>
  <br>
	<%= f.label :description, 'Description'%>
	<%= f.text_field :description%>
	<br>
  <br>
	<%= f.label :abstract, 'Abstract'%>
	<%= f.text_field :abstract%>
  <br>
  <br>
  <%= f.label :budget, 'Budget'%>
  <%= f.text_field :budget%>
  <br>
  <br>
  <%=f.submit button_name%>


  <%end%>
  <br>
  <%= link_to 'Back', projects_path %>

app/views/projects/edit.html.erb
<h1> Create New Project</h1>

<br>
<br>
<%= render 'form', button_name: 'Update' %>

<br>
<br>

app/views/projects/index.html.erb
<h1>Available Lists of Projects</h1>
<table>
<thead>
<th>Title</th>
<th>Description</th>
<th>Abstract</th>
<th>Bugdet</th>

</thead>
<tbody>

<% @projects.each do |project| %>

<tr>
	<td><%= project.title%></td>
	<td><%= project.abstract%></td>
	<td><%= project.description%></td>
	<td><%= project.budget%></td>

	<td><%= link_to 'Show', project_path(project.id) %></td>

	<td><%= link_to 'Edit', edit_project_path(project.id) %></td>
	<td><%= link_to "Delete", project_path(project.id),method: 'delete', confirm: 'Are u sure u want to delete?' %></td>


</tr>


<% end %>

</tbody>

</table>
<br>
<td><%= link_to 'Top Hits', top_hits_projects_path %></td>
<br>
<br>
<%= link_to 'Post project', new_project_path%>

app/views/projects/new.html.erb
<h1> Create New Project</h1>

<br>
<br>
<%= render 'form', button_name: 'add' %>
<br>
<br>

app/views/projects/show.html.erb
<h1><%= @project.title%></h1>

<%= @project.abstract%>
<%= @project.description%>
<%= @project.budget%>
<br>

<%=link_to 'Home', projects_path %>

app/views/projects/top_hits.html.erb
<h1>Top Projects</h1>
<table>
<thead>
<th>Title</th>
<th>Description</th>
<th>Abstract</th>
<th>Bugdet</th>

</thead>
<tbody>

<% @projects.each do |project| %>

<tr>
	<td><%= project.title%></td>
	<td><%= project.abstract%></td>
	<td><%= project.description%></td>
	<td><%= project.budget%></td>

	
</tr>

<% end %>

</tbody>

</table>